### ISSUE TITLE
What does this refer to?

### ISSUE THREAD

**Issue by CuteWaterBeary** [poiyomi/PoiyomiToonShader#55]
https://github.com/poiyomi/PoiyomiToonShader/blob/cfec9115b96f22c177eafe125d39f60cacac9bc4/_PoiyomiShaders/Scripts/poi-tools/PoiToolsDefinition.asmdef#L4

**Comment by rrazgriz** [comment]
That's the GUID for the Modular Shader System assembly definition, which doesn't exist in the free release. It's included in this asmdef because the free release is a subset of the Patreon release. 

![image](https://github.com/poiyomi/PoiyomiToonShader/assets/47901762/38f4b654-9079-4fbe-b308-6147475fefff)
